config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    collection do
      post :search
      get :search
    end
  end

  resources :responses do
    collection do
      post :filter
      get :filter
      post :init_survey
    end
  end
  
  resources :media_socials

  post '/add_user' => "users#create"
  put "/profiles" => "users#update_profile"
  get "/profile" => "users#profile"

  get "set_language/change_locale"

  root 'dashboard#index'

  resources :surveys do
    collection do
      post :filter
      get :filter

      get "status/:id" => "surveys#force_status", as: :force

      post :get_view
      get :reload
      post :reorder
      get :question_list
      get "preview/:id" => "surveys#preview", as: :preview
      get :add_row
      get :set_enable
      get :set_survey_session
      get :question_detail
      get :question_page
      get :reset_session
      
      post :set_question
      get :edit_question
      get :add_question
      get "manage_question/:section" => "surveys#manage_question", as: :manage_question
      post "manage_question/:section" => "surveys#manage_question", as: :manage_question_post
      
      post :set_logical
      get :edit_logical
      get :add_logical
      get "manage_logical/:section" => "surveys#manage_logical", as: :manage_logical
      post "manage_logical/:section" => "surveys#manage_logical", as: :manage_logical_post
      
      post :set_page
      get :edit_page
      get :add_page
      get "manage_page/:section" => "surveys#manage_page", as: :manage_page
      post "manage_page/:section" => "surveys#manage_page", as: :manage_page_post
    end
  end

end

app/views/questions/_checkbox.html.erb
<% current_response = session[current_user.id.to_s]['response'] %>

<% if question['varians']["image"].present? %>
	<div class="form-group half-size has-media">
		<%= image_tag question['varians']["image"].gsub("public/","/") %>
	</div>
<% end %>

<% if question['varians']["video"].present? %>
	<div class="form-group half-size has-media">
		<%= video_tag question['varians']["video"].gsub("public/","/") %>
	</div>
<% end %>

<div class="form-group clearfix half-size">	
	<% question['varians']['option'].each do |index, option| %>
		<div class="checkbox reset-width">
			<%
				if index.downcase=='other'
					index_name = index
				else
					index_name = option['label']
				end
			%>

			<%= check_box_tag "response[#{question['id']}][checkbox][#{index_name}]", 1, current_response[question['id'].to_s].present? ? current_response[question['id'].to_s]['checkbox'][index_name] : false, disabled: (disabled ? true : false), required: (question["required"].to_i==1 ? true : false), style: "margin-top:10px;" %>
			<%= label_tag "response_"+question['id'].to_s+"_checkbox_"+index_name.to_s, option["label"] %>
			
			<% if index.downcase=='other' %>
				<div class="col-sm-5 input-other">
					<%= text_field_tag "response[#{question['id']}][checkbox][#{index_name}_text]", current_response[question['id'].to_s].present? ? current_response[question['id'].to_s]['checkbox'][index_name + "_text"] : "", class: "form-control", disabled: (disabled ? true : false), placeholder: "Your question" %>
				</div>
			<% end %>
		</div>
	<% end %>
</div>

app/views/questions/_date.html.erb
<% current_response = session[current_user.id.to_s]['response'] %>

<% if question['varians']["image"].present? %>
	<div class="form-group half-size has-media">
		<%= image_tag question['varians']["image"].gsub("public/","/") %>
	</div>
<% end %>

<% if question['varians']["video"].present? %>
	<div class="form-group half-size has-media">
		<%= video_tag question['varians']["video"].gsub("public/","/") %>
	</div>
<% end %>

<div class="form-group half-size">
	<div class="range-date">
		<% if question['varians']['include_to'].to_i==1 %>
	    <%
		    if question['varians']['include_year'].to_i==1 && question['varians']['include_time'].to_i==0
		    	class_name = ["dpdyear1", "dpdyear2"]
		    elsif question['varians']['include_year'].to_i==0 && question['varians']['include_time'].to_i==1
		    	class_name = ["form_datetime", "form_datetime"]
		    elsif question['varians']['include_year'].to_i==1 && question['varians']['include_time'].to_i==1
		    	class_name = ["form_datetimeyear", "form_datetimeyear"]
		    else
		    	class_name = ["dpddefault1", "dpddefault2"]
		    end
	    %>
			<div class="input-group input-large">
				<input name="response[<%= question['id'] %>][date][date_start]" class="form-control range-date-control <%= class_name %>" placeholder="Start" <%= "disabled" if disabled %> <%= "required" if question["required"].to_i==1 %> value="<%= current_response[question['id'].to_s]['date']['date_start'] if current_response[question['id'].to_s].present? %>">
	      <span class="input-group-addon">To</span>
				<input name="response[<%= question['id'] %>][date][date_end]" class="form-control range-date-control" placeholder="End" <%= "disabled" if disabled %> <%= "required" if question["required"].to_i==1 %> value="<%= current_response[question['id'].to_s]['date']['date_end'] if current_response[question['id'].to_s].present? %>">
	    </div>
		<% else %>
	    <%
		    if question['varians']['include_year'].to_i==1 && question['varians']['include_time'].to_i==0
		    	class_name = "singleyear"
		    elsif question['varians']['include_year'].to_i==0 && question['varians']['include_time'].to_i==1
		    	class_name = "singletime"
		    elsif question['varians']['include_year'].to_i==1 && question['varians']['include_time'].to_i==1
		    	class_name = "singletimeyear"
		    else
		    	class_name = "singledefault"
		    end
	    %>
			<div class="col-sm-6">
				<input name="response[<%= question['id'] %>][date]" class="form-control range-date-control <%= class_name %>" placeholder="Date" <%= "disabled" if disabled %> <%= "required" if question["required"].to_i==1 %> value="<%= current_response[question['id'].to_s]['date'] if current_response[question['id'].to_s].present? %>">
	    </div>
		<% end %>
  </div>
</div>

app/views/questions/_index.html.erb
<% exclude_action ||= false %>
<div class="set-preview col-sm-12 form-horizontal" id="question-preview-<%= id %>">
	<div class="set-preview-header">
    <%= question['title'] %>
    <% unless exclude_action %>
			<span>
				<%= link_to '', edit_question_surveys_path(id: id), remote: true, :class => 'fa fa-pencil' %>
				<%= link_to '', manage_question_surveys_path(:duplicate, id: id), remote: true, :class => 'fa fa-copy' %>
				<%= link_to '', manage_question_surveys_path(:remove, id: id), remote: true, :class => 'fa fa-trash-o' %>
			</span>
		<% end %>
	</div>

	<div class="set-preview-body">
		<p class="set-tooltip"><%= question['help'] %></p>
		<%#= question %>
		<%= render "/questions/" + (question['type'].present? ? question['type'] : question['question_type']), disabled: disabled, question: question.is_a?(Hash) ? question : question.as_json %>
	</div>
</div>

app/views/questions/_logical.html.erb
<div class="set-preview col-sm-12" id="logical-preview-<%= id %>">
	<div class="set-preview-header">
		<span>
			<%= link_to '', edit_logical_surveys_path(id: id), remote: true, :class => 'fa fa-pencil' %>
			<%= link_to '', manage_logical_surveys_path(:remove, id: id), remote: true, :class => 'fa fa-trash-o' %>
		</span>

		<% question = session[current_user.id.to_s]["question"][id.to_i] %>
    <%= question["title"] %>
	</div>

	<div class="set-preview-body logical-preview form-horizontal" id="logical_questions-<%= id %>">
		<% logical['varians'].each do |id, varians| %>
			<%= render "/questions/logical_questions", varians: varians, question: question %>
		<% end %>
	</div>
</div>

app/views/questions/_page.html.erb
<% exclude_action ||= false %>
<% is_final ||= false %>
<% set_enable ||= false %>
<% is_background = is_background.present? ? is_background.to_s : 'false' %>
<%
	if is_final
	  background = page['background'].gsub("public/","/") if page.present? && page['background'].present?
	  set_background = (page['color'].present? ? "background: #{page['color']};" : (background.present? ? "background: url('#{background}') center center fixed; background-size: cover;" : ""))
	else
		set_background = ""
	end
%>
<div class="set-preview col-sm-12 <%= 'draggable' unless is_background=='true' || is_final==true %>" id="<%= is_background=='true' ? 'background' : 'page' %>-preview-<%= id %>" style="<%= set_background %>">
	<div class="set-preview-header <%= 'draggable-toucher' unless is_background=='true' || is_final %>">
    <% unless exclude_action %>
			<span>
				<%= link_to '', preview_surveys_path(id), target: "_blank", :class => 'fa fa-eye' if is_background=='true' %>
				<%= link_to '', edit_page_surveys_path(id: id, is_background: is_background), remote: true, :class => 'fa fa-pencil' %>
				<%= link_to '', manage_page_surveys_path(:remove, id: id, is_background: is_background), remote: true, :class => 'fa fa-trash-o' %>
			</span>
    <% end %>

    <% if set_enable %>
			<span>
				<%= check_box_tag "pages[is_enable][]", id, page['is_enable']=="true" ? true : false, id: "pages_is_enable_#{id}", onchange: "set_enable(this)", "data-id" => id %>
				<%= label_tag "pages_is_enable_#{id}", "Enable", style: "font-weight:normal;" %>
			</span>
    <% end %>

    <%= page['title'] %>

		<% if is_background=='true' %>
			<% unless exclude_action==true %>
				<p class="set-tooltip exclude-margin"><%= page['description'] %></p>
				
				<% if page['color'].present? %>
					<p class="set-tooltip"><%= page['color'] %></p>
				<% end %>
				<% if page['background'].present? %>
					<p class="set-tooltip"><%= page['background'] %></p>
				<% end %>
			
			<% else %>
				<p class="set-tooltip"><%= page['description'] %></p>
			
			<% end %>
		<% else %>
			<p class="set-tooltip"><%= page['description'] %></p>
		
		<% end %>
	</div>

	<% unless is_background=='true' %>
		<div class="set-preview-body page-preview draggable-wrapper" id="page_questions-<%= id %>">
			<%= render "/questions/page_questions", page: page, id: id, exclude_action: exclude_action, is_background: is_background, is_final: is_final %>
		</div>
  <% end %>
</div>

app/views/questions/_paragraph_text.html.erb
<% current_response = session[current_user.id.to_s]['response'] %>

<% if question['varians']["image"].present? %>
	<div class="form-group half-size has-media">
		<%= image_tag question['varians']["image"].gsub("public/","/") %>
	</div>
<% end %>

<% if question['varians']["video"].present? %>
	<div class="form-group half-size has-media">
		<%= video_tag question['varians']["video"].gsub("public/","/") %>
	</div>
<% end %>

<div class="form-group half-size">
	<textarea name="response[<%= question['id'] %>][paragraph_text]" class="form-control" <%= "disabled" if disabled %> <%= "required" if question["required"].to_i==1 %> <%= "min=#{question['varians']['number']}".html_safe if question['varians']['validate'].present? && question['varians']['type'] == "minimum" %> <%= "max=#{question['varians']['number']}".html_safe if question['varians']['validate'].present? && question['varians']['type'] == "maximum" %> placeholder="Your question"><%= current_response[question['id'].to_s]['paragraph_text'] if current_response[question['id'].to_s].present? %></textarea>
</div>

app/views/questions/_percentage_scale.html.erb
<% current_response = session[current_user.id.to_s]['response'] %>

<% if question['varians']["image"].present? %>
	<div class="form-group half-size has-media">
		<%= image_tag question['varians']["image"].gsub("public/","/") %>
	</div>
<% end %>

<% if question['varians']["video"].present? %>
	<div class="form-group half-size has-media">
		<%= video_tag question['varians']["video"].gsub("public/","/") %>
	</div>
<% end %>

<div class="form-group half-size">
  <input class="slider-selector" type="text" name="response[<%= question['id'] %>][percentage_scale]" value="0;100" data-type="single" data-step="<%= question['increment'] %>" data-postfix="" data-hasgrid="true" <%= "disabled" if disabled %> <%= "required" if question["required"].to_i==1 %> data-from="<%= current_response[question['id'].to_s].present? ? current_response[question['id'].to_s]['date'] : question['answer'] %>"/>
	
	<span class="pull-left">
		<%= question['varians']['text_before'] %>
	</span>

	<span class="pull-right">
		<%= question['varians']['text_after'] %>
	</span>
</div>

app/views/questions/_radio_button.html.erb
<% current_response = session[current_user.id.to_s]['response'] %>

<% if question['varians']["image"].present? %>
	<div class="form-group half-size has-media">
		<%= image_tag question['varians']["image"].gsub("public/","/") %>
	</div>
<% end %>

<% if question['varians']["video"].present? %>
	<div class="form-group half-size has-media">
		<%= video_tag question['varians']["video"].gsub("public/","/") %>
	</div>
<% end %>

<div class="form-group clearfix half-size">
	<% question['varians']['options'].each do |index, option| %>
		<div class="checkbox reset-width">
			<%
				if index.downcase=='other'
					index_name = index
				else
					index_name = option['label']
				end
			%>
			<%= radio_button_tag "response[#{question['id']}][radio_button][answer]", index_name, current_response[question['id'].to_s].present? ? (current_response[question['id'].to_s]['radio_button']['answer']==index_name ? true : false) : false, disabled: (disabled ? true : false), required: (question["required"].to_i==1 ? true : false) %>
			<%= label_tag "response[#{question['id']}][radio_button]_" + index_name, option["label"] %>
			
			<% if index.downcase=='other' %>
				<div class="col-sm-5 input-other">
					<%= text_field_tag "response[#{question['id']}][radio_button][#{index_name}]", current_response[question['id'].to_s].present? ? current_response[question['id'].to_s]['radio_button'][index_name] : "", class: "form-control", disabled: (disabled ? true : false) %>
				</div>
			<% end %>
		</div>
	<% end %>
</div>

app/views/questions/_radio_button_grid.html.erb
<% current_response = session[current_user.id.to_s]['response'] %>

<% weighting = ["--", "-", "+", "++"] %>

<% if question['varians']["image"].present? %>
	<div class="form-group half-size has-media">
		<%= image_tag question['varians']["image"].gsub("public/","/") %>
	</div>
<% end %>

<% if question['varians']["video"].present? %>
	<div class="form-group half-size has-media">
		<%= video_tag question['varians']["video"].gsub("public/","/") %>
	</div>
<% end %>

<table class="grid-table">
	<thead>
		<td></td>
		<% question["varians"]["option"]["column"].each do |id, column| %>
			<td><%= column["label"] %></td>
		<% end %>
		<% if question["varians"]["weighting"].to_i == 1  %>
			<td class="weighting">
				<table>
					<thead>
					<% weighting.each do |weight| %>
						<td><%= weight %></td>
					<% end %>
					</thead>
				</table>
			</td>
		<% end %>
	</thead>
	<tbody>
		<% question["varians"]["option"]["row"].each do |row_id, row| %>
			<tr>
				<td><%= row["label"] %></td>
				<% question["varians"]["option"]["column"].each do |col_id, column| %>
					<td>
						<%= radio_button_tag "response[#{question['id']}][radio_button_grid][#{row_id}][answer]", col_id, current_response[question['id'].to_s].present? ? (current_response[question['id'].to_s]['radio_button_grid'][row_id]['answer']==col_id ? true : false ) : false, required: (question["required"].to_i==1 ? true : false) %>
					</td>
				<% end %>

				<% if question["varians"]["weighting"].to_i == 1  %>
					<td class="weighting">
						<table>
							<tbody>
								<% weighting.each_with_index do |index, weight| %>
									<td>
										<%= radio_button_tag "response[#{question['id']}][radio_button_grid][#{row_id}][weighting]", index, current_response[question['id'].to_s].present? ? (current_response[question['id'].to_s]['radio_button_grid'][row_id]['weighting']==index ? true : false) : false, disabled: (disabled ? true : false), required: (question["required"].to_i==1 ? true : false) %>
									</td>
								<% end %>
							</tbody>
						</table>
					</td>
				<% end %>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/questions/_radio_button_scale.html.erb
<% current_response = session[current_user.id.to_s]['response'] %>

<% if question['varians']["image"].present? %>
	<div class="form-group half-size has-media">
		<%= image_tag question['varians']["image"].gsub("public/","/") %>
	</div>
<% end %>

<% if question['varians']["video"].present? %>
	<div class="form-group half-size has-media">
		<%= video_tag question['varians']["video"].gsub("public/","/") %>
	</div>
<% end %>

<table class="grid-table">
	<tbody>
		<% question["varians"]["option"].each do |opt_id, option| %>
			<tr>
				<td><%= option["text_before"] %></td>
				<% (0..question['varians']['increment'].to_i-1).each do |index|  %>
					<td>
						<%= radio_button_tag "response[#{question['id']}][radio_button_scale][#{opt_id}]", index, current_response[question['id'].to_s].present? ? (current_response[question['id'].to_s]['radio_button_scale'][opt_id]==index ? true : false) : false, disabled: (disabled ? true : false), required: (question["required"].to_i==1 ? true : false) %>
					</td>
				<% end %>
				<td><%= option["text_after"] %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/questions/_ranking.html.erb
<% current_response = session[current_user.id.to_s]['response'] %>

<% question["varians"]["option"].each do |id, option| %>
	<div class="form-group">
		<div class="ranking-value">
			<%= select_tag "response[#{question['id']}][ranking][#{option['label']}]", options_for_select((question["varians"]["ranking"]["min"].to_i..question["varians"]["ranking"]["max"].to_i).map { |value| value }, current_response[question['id'].to_s].present? ? current_response[question['id'].to_s]['ranking'][option['label']] : (question["answer"].present? ? question["answer"] : question["varians"]["ranking"]["min"].to_i)), disabled: (disabled ? true : false), required: (question["required"].to_i==1 ? true : false), class: "form-control" %>
		</div>
		<%= label_tag "response[#{question['id']}][ranking][#{option['label']}]", option['label'] %>
	</div>
<% end %>

app/views/questions/_textbox.html.erb
<% current_response = session[current_user.id.to_s]['response'] %>

<% if question['varians']["image"].present? %>
	<div class="form-group half-size has-media">
		<%= image_tag question['varians']["image"].gsub("public/","/") %>
	</div>
<% end %>

<% if question['varians']["video"].present? %>
	<div class="form-group half-size has-media">
		<%= video_tag question['varians']["video"].gsub("public/","/") %>
	</div>
<% end %>

<div class="form-group half-size">
	<input class="form-control" <%= "disabled" if disabled %> name="response[<%= question['id'] %>][textbox]" <%= "required" if question["required"].to_i==1 %> type="<%= question['varians']['validate'].present? ? question['varians']['type'] : 'text' %>" <%= "onkeypress='return event.charCode >= 48 && event.charCode <= 57'".html_safe if question['varians']['validate'].present? && question['varians']['type'] == "number" %> placeholder="Your question" value="<%= current_response[question['id'].to_s]['textbox'] if current_response[question['id'].to_s].present? %>">
</div>

app/views/questions/_textbox_grid.html.erb
<% current_response = session[current_user.id.to_s]['response'] %>

<% weighting = ["--", "-", "+", "++"] %>

<% if question['varians']["image"].present? %>
	<div class="form-group half-size has-media">
		<%= image_tag question['varians']["image"].gsub("public/","/") %>
	</div>
<% end %>

<% if question['varians']["video"].present? %>
	<div class="form-group half-size has-media">
		<%= video_tag question['varians']["video"].gsub("public/","/") %>
	</div>
<% end %>

<table class="grid-table">
	<thead>
		<td></td>
		<% question["varians"]["option"]["column"].each do |id, column| %>
			<td><%= column["label"] %></td>
		<% end %>
	</thead>
	<tbody>
		<% question["varians"]["option"]["row"].each do |row_id, row| %>
			<tr>
				<td><%= row["label"] %></td>
				<% question["varians"]["option"]["column"].each do |col_id, column| %>
					<td>
						<input name="response[<%= question['id'] %>][textbox_grid][<%= row_id %>][<%= col_id %>]" class="form-control" <%= "disabled" if disabled %> <%= "required" if question["required"].to_i==1 %> type="<%= question['varians']['validate'].present? ? question['varians']['type'] : 'text' %>" <%= "onkeypress='return event.charCode >= 48 && event.charCode <= 57'".html_safe if question['varians']['validate'].present? && question['varians']['type'] == "number" %> value="<%= current_response[question['id'].to_s]['textbox_grid'][row_id][col_id] if current_response[question['id'].to_s].present? %>">
					</td>
				<% end %>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/questions/_upload.html.erb
<% current_response = session[current_user.id.to_s]['response'] %>

<%#= question %>

<% if question['varians']["image"].present? %>
	<div class="form-group half-size has-media">
		<%= image_tag question['varians']["image"].gsub("public/","/") %>
	</div>
<% end %>

<% if question['varians']["video"].present? %>
	<div class="form-group half-size has-media">
		<%= video_tag question['varians']["video"].gsub("public/","/") %>
	</div>
<% end %>

<div class="form-group half-size has-upload">
	<div class="fileUpload btn btn-primary <%= 'disabled' if disabled %>">
    <span><%= question['varians']['label'] %></span>
		<input type="file" placeholder="<%= question['varians']['label'] %>" class="upload" <%= "disabled" if disabled %> value="<%= question['answer'] %>" <%= "required" if question['required'].to_i==1 %> name="response[<%= question['id'] %>][upload]" id="response_<%= question['id'] %>_upload">
	</div>
	<span id="response_<%= question['id'] %>_upload_text">Choose File</span>
</div>

<script type="text/javascript">
	document.getElementById("response_<%= question['id'] %>_upload").onchange = function () {
		if (this.value == "") {
	  	this_value = "Choose File";
		} else{
	  	this_value = "..."+this.value.substr(this.value.length - 20);
		};
    document.getElementById("response_<%= question['id'] %>_upload_text").innerHTML = this_value;
	};
</script>