config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    collection do
      post :search
      get :search
    end
  end

  resources :responses do
    collection do
      post :filter
      get :filter
      post :init_survey
    end
  end
  
  resources :media_socials

  post '/add_user' => "users#create"
  put "/profiles" => "users#update_profile"
  get "/profile" => "users#profile"

  get "set_language/change_locale"

  root 'dashboard#index'

  resources :surveys do
    collection do
      post :filter
      get :filter

      get "status/:id" => "surveys#force_status", as: :force

      post :get_view
      get :reload
      post :reorder
      get :question_list
      get "preview/:id" => "surveys#preview", as: :preview
      get :add_row
      get :set_enable
      get :set_survey_session
      get :question_detail
      get :question_page
      get :reset_session
      
      post :set_question
      get :edit_question
      get :add_question
      get "manage_question/:section" => "surveys#manage_question", as: :manage_question
      post "manage_question/:section" => "surveys#manage_question", as: :manage_question_post
      
      post :set_logical
      get :edit_logical
      get :add_logical
      get "manage_logical/:section" => "surveys#manage_logical", as: :manage_logical
      post "manage_logical/:section" => "surveys#manage_logical", as: :manage_logical_post
      
      post :set_page
      get :edit_page
      get :add_page
      get "manage_page/:section" => "surveys#manage_page", as: :manage_page
      post "manage_page/:section" => "surveys#manage_page", as: :manage_page_post
    end
  end

end

app/views/wizards/_backgrounds.html.erb
<div id="background-preview" class="clearfix">
  <% if session["#{current_user.id.to_s}"]["pages"].present? %>
		<% session["#{current_user.id.to_s}"]["pages"].each do |id, pages| %>
			<%= render "/questions/page", page: pages, id: id, is_background: true %>
		<% end %>
	<% end %>
</div>
<div id="set-background-form"></div>

app/views/wizards/_finals.html.erb
<div id="final-preview" class="clearfix">
  <% if session["#{current_user.id.to_s}"]["pages"].present? %>
		<% session["#{current_user.id.to_s}"]["pages"].each do |id, pages| %>
			<%= render "/questions/page", page: pages, id: id, is_background: false, exclude_action: true, is_final: true, set_enable: true %>
		<% end %>
	<% end %>
</div>

app/views/wizards/_head_question.html.erb
<% id ||= 0 %>
<% current_value = session[current_user.id.to_s]['question'][id.to_i] %>
<div class="form-group ">
	<%= label_tag "question[title]", "Question title", class: "col-sm-2 col-sm-2 control-label" %>
  <div class="col-sm-8">
    <%= text_field_tag "question[title]", current_value.present? ? current_value['title'] : "", class: 'form-control', :required => true, placeholder: "Question title" %>
  </div>
</div>

<div class="form-group ">
	<%= label_tag "question[help]", "Help text", class: "col-sm-2 col-sm-2 control-label" %>
  <div class="col-sm-8">
    <%= text_field_tag "question[help]", current_value.present? ? current_value['help'] : "", class: 'form-control', placeholder: "Help text" %>
  </div>
</div>

app/views/wizards/_logicals.html.erb
<div id="logical-preview" class="clearfix draggable-wrapper">
  <% if session["#{current_user.id.to_s}"]["logical"].present? %>
		<% session["#{current_user.id.to_s}"]["logical"].each do |id, logical| %>
			<%= render "/questions/logical", logical: logical, id: id %>
		<% end %>
	<% end %>
</div>
<div id="set-logical-form"></div>

<%= link_to "Add Logical", add_logical_surveys_path, remote: true, class: "btn btn-primary" %>
<div id="close-logical-link" class="hide close-link">
  <%= link_to "Cancel", add_logical_surveys_path(cancel: true), remote: true, class: "btn btn-primary" %>
</div>

app/views/wizards/_pages.html.erb
<div id="page-preview" class="clearfix draggable-wrapper">
  <% if session["#{current_user.id.to_s}"]["pages"].present? %>
		<% session["#{current_user.id.to_s}"]["pages"].each do |id, pages| %>
			<%= render "/questions/page", page: pages, id: id, is_background: false %>
		<% end %>
	<% end %>
</div>
<div id="set-page-form"></div>

<%= link_to "Add Page", add_page_surveys_path, remote: true, class: "btn btn-primary" %>
<div id="close-page-link" class="hide close-link">
  <%= link_to "Cancel", add_page_surveys_path(cancel: true), remote: true, class: "btn btn-primary" %>
</div>

app/views/wizards/_questions.html.erb
<div id="question-preview" class="clearfix">
  <% if session["#{current_user.id.to_s}"]["question"].present? %>
  	<% session["#{current_user.id.to_s}"]["question"].each do |id, question| %>
  		<%= render "/questions/index", question: question, id: id, disabled: true %>
    <% end %>
	<% end %>
</div>
<div id="set-question-form"></div>
<%= link_to "Add Question", add_question_surveys_path, remote: true, class: "btn btn-primary" %>
<div id="close-question-link" class="hide close-link">
  <%= link_to "Cancel", add_question_surveys_path(cancel: true), remote: true, class: "btn btn-primary" %>
</div>

app/views/wizards/_set_logical.html.erb
<% id ||= 0 %>
<% current_value = session[current_user.id.to_s]['logical'][id.to_i] %>

<%= form_tag id == 0 ? set_logical_surveys_path : manage_logical_post_surveys_path(:update, id: id), class: "form-horizontal", :multipart => true, id: "new_set_logical" do %>
	<%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
	<div class="form-group">
    <div class="col-sm-8">
      <% options = session[current_user.id.to_s]['question'].map{|question_id, question| (([question['title'], question_id] if question['varians']['logical'] == "1") if question['varians'].present?) }.compact  %>
      <%= select_tag "logical[target]", options_for_select(options, current_value.present? ? current_value["target"] : "-"), :prompt => "Select question...", :class => "form-control", :onclick => "question_detail(this, 'head', 0)" %>
    </div>
  </div>

  <hr/>

  <div id="logical_content_wrapper">
    <% if current_value.present? %>
      <%= render '/values/logical', id: id, index: 0 %>
    <% end %>
  </div>

  <div class="form-group">
    <div class="col-sm-4">
      <%= button_tag "Done", type: "submit", class: "btn btn-primary" %>
      <%= link_to "Cancel", edit_logical_surveys_path(id: id, cancel: true), remote: true, class: "btn btn-primary" if id.to_i > 0 %>
    </div>
  </div>
<% end %>

app/views/wizards/_set_page.html.erb
<% id ||= 0 %>
<% is_background = params[:is_background].present? ? params[:is_background].to_s : 'false' %>
<% current_value = session[current_user.id.to_s]['pages'][id.to_i] %>

<%= form_tag id == 0 ? set_page_surveys_path : manage_page_post_surveys_path(:update, id: id, is_background: is_background), class: "form-horizontal", :multipart => true, id: "new_set_page", onsubmit: "set_loader()" do %>
	<%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
	<div class="form-group <%= 'hide' if is_background=='true' %>">
    <%= label_tag "pages[title]", "Page title", class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= text_field_tag "pages[title]", current_value.present? ? current_value['title'] : "", class: 'form-control', :required => true, placeholder: "Page title" %>
    </div>
  </div>

  <div class="form-group <%= 'hide' if is_background=='true' %>">
    <%= label_tag "pages[description]", "Page description", class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= text_area_tag "pages[description]", current_value.present? ? current_value['description'] : "", class: 'form-control', :required => true, placeholder: "Page description" %>
    </div>
  </div>

  <div class="form-group <%= 'hide' unless is_background=='true' %>">
    <%= label_tag "pages[background]", "Background", class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= file_field_tag "pages[background]", { value: (current_value.present? ? current_value['background'] : ""), class: 'form-control', placeholder: "Background"} %>
      <span class="help-block">Leave it blank if you want background using color</span>
    </div>
  </div>

  <div class="form-group <%= 'hide' unless is_background=='true' %>">
    <%= label_tag "pages[color]", "Color", class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= text_field_tag "pages[color]", current_value.present? ? current_value['color'] : "", class: 'colorpicker-default form-control', placeholder: "Color" %>
      <span class="help-block">Leave it blank if you want background using image</span>
    </div>
  </div>

  <% unless is_background=='true' %>
    <hr/>

    <div id="page_content">
      <div class="advance panel box">
        <div class="advance-heading">
          <span class="tools">
            <a href="javascript:;" class="fa fa-plus-square"></a>
          </span>
          List Questions
        </div>

        <div id="add_question_page" class="advance-body" style="display: none;">
          <div class="clearfix has-button">
            <div class="col-sm-6">
              <% if current_value.present? %>
                <% temp_questions = current_value['questions'] %>
                <%= select_tag "pages[questions][]", options_for_select(@options ,temp_questions.first), :prompt => "Select question...", :class => "form-control" %>
              <% else %>
                <%= select_tag "pages[questions][]", options_for_select(@options ,'-'), :prompt => "Select question...", :class => "form-control" %>
              <% end %>
            </div>
            <div class="col-sm-6">
              <%= link_to "Add New +", "#", id: "add_new_question_button", class: "btn btn-primary pull-right", onclick: "get_question_lists(#{id})" %>
            </div>
          </div>
          <% if current_value.present? %>
            <% temp_questions.each do |question| %>
              <% unless question == temp_questions.first %>
                <% if question.length>0 %>
                  <div class="clearfix has-button">
                    <div class="col-sm-6">
                      <%= select_tag "pages[questions][]", options_for_select(@options ,question), :prompt => "Select question...", :class => "form-control" %>
                    </div>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-4">
      <%= button_tag "Done", type: "submit", class: "btn btn-primary" %>
      <%= link_to "Cancel", edit_page_surveys_path(id: id, cancel: true, is_background: is_background), remote: true, class: "btn btn-primary" if id.to_i > 0 %>
    </div>
  </div>
<% end %>

app/views/wizards/_set_question.html.erb
<% id ||= 0 %>
<% current_value = session[current_user.id.to_s]['question'][id.to_i] %>
<%= form_tag id == 0 ? set_question_surveys_path : manage_question_post_surveys_path(:update, id: id), class: "form-horizontal", :multipart => true, id: "new_set_question", onsubmit: "set_loader()" do %>
<!-- $($(this).find('button[type=submit]')[0]).prop('disabled', true); $($(this).find('button[type=submit]')[0]).prop('disabled', true); return false; -->
	<%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
	<div id="question_head">
		<%= render "/wizards/head_question", id: id %>
	</div>

  <div class="form-group ">
  	<%= label_tag "question[type]", "Question type", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= select_tag "question[type]", options_for_select(@question_type, current_value.present? ? current_value['type'] : '-'), :prompt => "Select question type...", :class => "form-control", :onchange => "changeField(this);" %>
    </div>
  </div>

  <hr/>

  <div id="question_content"></div>
<% end %>