config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    collection do
      post :search
      get :search
    end
  end

  resources :responses do
    collection do
      post :filter
      get :filter
      post :init_survey
    end
  end
  
  resources :media_socials

  post '/add_user' => "users#create"
  put "/profiles" => "users#update_profile"
  get "/profile" => "users#profile"

  get "set_language/change_locale"

  root 'dashboard#index'

  resources :surveys do
    collection do
      post :filter
      get :filter

      get "status/:id" => "surveys#force_status", as: :force

      post :get_view
      get :reload
      post :reorder
      get :question_list
      get "preview/:id" => "surveys#preview", as: :preview
      get :add_row
      get :set_enable
      get :set_survey_session
      get :question_detail
      get :question_page
      get :reset_session
      
      post :set_question
      get :edit_question
      get :add_question
      get "manage_question/:section" => "surveys#manage_question", as: :manage_question
      post "manage_question/:section" => "surveys#manage_question", as: :manage_question_post
      
      post :set_logical
      get :edit_logical
      get :add_logical
      get "manage_logical/:section" => "surveys#manage_logical", as: :manage_logical
      post "manage_logical/:section" => "surveys#manage_logical", as: :manage_logical_post
      
      post :set_page
      get :edit_page
      get :add_page
      get "manage_page/:section" => "surveys#manage_page", as: :manage_page
      post "manage_page/:section" => "surveys#manage_page", as: :manage_page_post
    end
  end

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :user
  has_many :survey_pages
  has_many :survey_responses
  has_many :survey_questions

  validates :name, presence: true, uniqueness: true

  self.per_page = 5

   default_scope { order("period_start desc") } 
  
  def self.set_per_page(number)
    self.per_page = number
  end

  def self.get_responses_count(surveys)
    total_responses = 0 
    surveys.each do |survey|
      total_responses += survey.survey_responses.count
    end
    return total_responses
  end

  def self.get_all_responses_count(surveys)
    total_responses = 0 
    surveys.each do |survey|
      total_responses += User.all.count
    end
    return total_responses
  end

  def is_user_response(user)
    self.survey_responses.select{|response| response if response.user_id==user}
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :authenticate_admin, except: [:index, :show]
  before_action :new_survey
  before_action :set_survey, only: [:show, :edit, :update, :destroy, :force_status]
  before_action :set_session

	# controller section
	def index
		if params[:survey].present?
  		@survey = Survey.new(survey_params)
  		
  		params_survey = params[:survey]
	  	
	  	params_name = params_survey[:name].upcase.gsub("'", "\\\'").gsub("\"", "\\\"")

	  	params_period_start = change_format(params_survey[:period_start]) if params_survey[:period_start].present?
	  	params_period_end = change_format(params_survey[:period_end]) if params_survey[:period_end].present?
	  	params_status = params_survey[:status].upcase unless params_survey[:status] == "all"

	  	puts params_period_start

	    where_clauses = []
	    where_clauses << "UPPER(name) LIKE '%#{params_name}%'" if params_name.present?
	    where_clauses << "period_start >= '#{params_period_start}'" if params_period_start.present?
	    where_clauses << "period_end <= '#{params_period_end}'" if params_period_end.present?
	    where_clauses << "UPPER(status) = '#{params_status}'" if params_status.present?

	    base_survey = Survey.where(where_clauses.join(" AND "))
  	else
  		@survey = Survey.new
    	base_survey = Survey.all
  	end

    @surveys_count = base_survey.count
    @surveys = base_survey.paginate(:page => params[:page])

    respond_to do |format|
      format.html
      format.js
    end
	end

	def filter
		if params[:survey].present?
  		@survey = Survey.new(survey_params)
  		
  		params_survey = params[:survey]
	  	
	  	params_name = params_survey[:name].upcase.gsub("'", "\\\'").gsub("\"", "\\\"")

	  	params_period_start = change_format(params_survey[:period_start]) if params_survey[:period_start].present?
	  	params_period_end = change_format(params_survey[:period_end]) if params_survey[:period_end].present?
	  	params_status = params_survey[:status].upcase unless params_survey[:status] == "all"

	  	puts params_period_start

	    where_clauses = []
	    where_clauses << "UPPER(name) LIKE '%#{params_name}%'" if params_name.present?
	    where_clauses << "period_start >= '#{params_period_start}'" if params_period_start.present?
	    where_clauses << "period_end <= '#{params_period_end}'" if params_period_end.present?
	    where_clauses << "UPPER(status) = '#{params_status}'" if params_status.present?

	    base_survey = Survey.where(where_clauses.join(" AND "))
  	else
  		@survey = Survey.new
    	base_survey = Survey.all
  	end

    @surveys_count = base_survey.count
    @surveys = base_survey.paginate(:page => params[:page])

    respond_to do |format|
      format.html { render :index }
      format.js { render :index }
    end
	end
	
	def new
	end

	def create
		# params[:survey][:period_start].to_date.strftime("%Y-%m-%d %H:%M:%S")
		# params[:survey][:period_start] = params[:survey][:period_start].to_date.strftime("%Y-%m-%d")
		# params[:survey][:period_end] = params[:survey][:period_end].to_date.strftime("%Y-%m-%d")
		
		default_period_start = params[:survey][:period_start]
		default_period_end = params[:survey][:period_end]

		params[:survey][:status], save_status = initialize_date(params[:survey])

		current_session = session[current_user.id.to_s]
		temp_session_question = {}

		params[:survey][:user_id] = current_user.id
		# params[:survey][:name] = params[:survey][:name] + DateTime.now.to_s

		survey = Survey.new(survey_params)
		if survey.save && save_status
			current_session["pages"].each do |key, pages|
				if pages.present?
					survey_page = SurveyPage.new
					survey_page.survey_id = survey.id
					survey_page.title = pages["title"]
					survey_page.description = pages["description"]
					survey_page.background = Rails.root.join(pages["background"]).open if pages["background"].present?
					survey_page.color = pages["color"]
					survey_page.order = pages["order"]
					survey_page.save

					if pages["question_order"].present?
						pages["question_order"].each do |index, question_id|
							if current_session["question"][question_id.to_i].present?
								question = current_session["question"][question_id.to_i]
								if current_session["logical"][question["id"].to_i].present?
									question["varians"]["logical_value"] = current_session["logical"][question["id"].to_i]["varians"]
								end
								
								question["varians"] = {} unless question["varians"].present?
								question["varians"]["session_id"] = question_id

								survey_question = SurveyQuestion.new
								survey_question.title = question["title"]
								survey_question.help = question["help"]
								survey_question.question_type = question["type"]
								survey_question.varians = question["varians"] #.to_a.to_s
								survey_question.required = question["required"].present? ? 1 : 0
								survey_question.answer = question["answer"].to_s
								survey_question.order = index
								survey_question.survey_page_id = survey_page.id
								survey_question.survey_id = survey.id
								survey_question.save

								temp_session_question[question_id.to_i] = question
								current_session["question"][question_id.to_i] = nil
							end
						end
					end
					# current_session["pages"][key] = {}
				end
			end

			# current_session["question"].each do |key, question|
			# 	if question.present?
			# 		if current_session["logical"][question["id"].to_i].present?
			# 			question["varians"]["logical_value"] = current_session["logical"][question["id"].to_i]["varians"]
			# 			question["varians"]["session_id"] = question_id
			# 		end

			# 		survey_question = SurveyQuestion.new
			# 		survey_question.title = question["title"]
			# 		survey_question.help = question["help"]
			# 		survey_question.question_type = question["type"]
			# 		survey_question.varians = question["varians"] #.to_a.to_s
			# 		survey_question.required = question["required"].present? ? 1 : 0
			# 		survey_question.answer = question["answer"].to_s
			# 		survey_question.survey_id = survey.id
			# 		survey_question.save
			# 	end
			# end

			session[current_user.id.to_s]["question"] = session[current_user.id.to_s]["question"].merge(temp_session_question)

			if survey.survey_pages.count != survey.survey_pages.last.order
				survey.survey_pages.each_with_index do |survey, index|
					survey.survey_questions.each do |question|
						question.update_attribute(:survey_page_id, index)
					end
					survey.update_attribute(:order, index)
				end
			end

			redirect_to reset_session_surveys_path
		else
			params[:survey][:period_start] = default_period_start
			params[:survey][:period_end] = default_period_end

			if save_status==false
				survey.errors.add(:period_start, "need to set before period end")
			end

			@survey = survey

			render :new
		end

		# render json: params
		# render json: session[current_user.id.to_s]
	end

	def update
		default_period_start = params[:survey][:period_start]
		default_period_end = params[:survey][:period_end]

		params[:survey][:status], save_status = initialize_date(params[:survey])

		if @survey.update(survey_params) && save_status
			@cancel = 'true'
			respond_to do |format|
	      format.js { render :edit }
	      format.html { redirect_to surveys_path }
	 		end
		else
			params[:survey][:period_start] = default_period_start
			params[:survey][:period_end] = default_period_end

			if save_status==false
				@survey.errors.add(:period_start, "need to set before period end")
			end

			respond_to do |format|
	      format.js { render :edit }
	      format.html { redirect_to surveys_path }
	 		end
		end
	end

	def edit
		@cancel = params[:cancel]

		if @survey.status=="open"
			@survey.update_attribute(:status, "closed")
			@cancel = 'true'
		end
	end

	def destroy
		@survey.destroy
		redirect_to surveys_path
	end

	def show
		render layout: false
	end

	def reset_session
  	session[current_user.id.to_s].clear
  	redirect_to surveys_path
	end

	def force_status
	end

	# question section
	def set_question
		last_record = session[current_user.id.to_s]['question'].values.last
		current_id = (last_record.present? ? last_record['id'].to_i : 0) + 1

		if params[:question].present?
			params[:question][:id] = current_id
			params[:question][:order] = current_id

			if params[:question][:varians].present?
				params[:question][:varians][:include_page] = "true"
				params[:question][:varians][:image] = upload_image(params[:question][:varians][:image]) if params[:question][:varians][:image].present?
				params[:question][:varians][:video] = upload_image(params[:question][:varians][:video]) if params[:question][:varians][:video].present?
			end

			session[current_user.id.to_s]['question'][current_id] = params[:question]

			# if params[:question][:varians].present?
			# 	if params[:question][:varians][:logical].present?
			# 		if params[:question][:varians][:logical] == 1
			# 			session[current_user.id.to_s]['logical'] << current_id
			# 		end
			# 	end
			# end
		end
		respond_to do |format|
      format.js
      format.html {redirect_to new_survey_path}
 		end
	end

	def edit_question
	end

	def add_question
	end

	def manage_question
		if params[:section] == "remove"
			if params[:id]
				if session[current_user.id.to_s]['question'][params[:id].to_i].present?
					session[current_user.id.to_s]['question'][params[:id].to_i] = nil

					session[current_user.id.to_s]['question'] = session[current_user.id.to_s]['question'].compact
				else
					@error = "unable to remove question!"
				end
			else
				@error = "unable to remove question!"
			end

		elsif params[:section] == "update"
			if params[:id]
				if session[current_user.id.to_s]['question'][params[:id].to_i].present?
					params[:question][:id] = params[:id]
					params[:question][:order] = params[:id]
					
					if params[:question][:varians][:image].present?
						params[:question][:varians][:image] = upload_image(params[:question][:varians][:image]) 
					else

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_edit.html.erb
<tr id="survey_<%= survey.id %>">
  <!-- <td><%#= link_to survey.name, survey, :target => "_blank" %></td>
  <td><%#= survey.period_start.strftime("%d %B %Y") %></td>
  <td><%#= survey.period_end.strftime("%d %B %Y") %></td>
  <td><%#= survey.survey_questions.count %></td>
  <td><%#= survey.survey_pages.count %></td>
  <td><%#= survey.status.capitalize %></td> -->
  <td colspan="7">
    <%= form_for @survey, html: {class: 'form-horizontal', :multipart => true, method: :put, :remote => true} do |f| %>
      <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
      <% if @survey.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>
          <ul>
          <% @survey.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= label_tag :period, "Period", class: "col-sm-2 control-label" %>
        <div class="col-sm-4">
          <div class="input-group input-large" >
            <%= f.text_field :period_start, value: f.object.period_start.strftime("%m/%d/%Y"), class: 'datepicker form-control dpd12', 'data-date-format' => "mm/dd/yyyy", placeholder: 'From', :required => true %>
            <span class="input-group-addon">To</span>
            <%= f.text_field :period_end, value: f.object.period_end.strftime("%m/%d/%Y"), class: 'datepicker form-control dpd22', 'data-date-format' => "mm/dd/yyyy", placeholder: 'To', :required => true %>
          </div>
          <span class="help-block">Select date range</span>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-8 col-sm-offset-2">
          <%= f.submit "Save", class: "btn btn-primary", id: "new_survey_submit" %>
          <%= link_to "Cancel", edit_survey_path(survey, cancel: true), remote: true, class: "btn btn-default" %>
        </div>
      </div>
    <% end %>
  </td>
</tr>

app/views/surveys/_survey.html.erb
<tr id="survey_<%= survey.id %>">
  <td><%= survey.is_user_response(current_user.id).present? ? survey.name : (link_to survey.name, survey, :target => "_blank") %></td>
  <td><%= survey.period_start.strftime("%d %B %Y") %></td>
  <td><%= survey.period_end.strftime("%d %B %Y") %></td>
  <td><%= survey.survey_questions.count %></td>
  <td><%= survey.survey_pages.count %></td>
  <td><%= survey.status.capitalize %></td>
  <td>
    <% if survey.user_id == current_user.id %>
      <%= link_to 'Delete', survey_path(survey), :confirm => 'Are you sure?', :method => :delete %>
      <%= link_to survey.status=="open" ? "Close" : "Reopen", edit_survey_path(survey, cancel: false), remote: true %>
    <% else %>
      No action available
    <% end %>
  </td>
</tr>

app/views/surveys/_surveys.html.erb
<table class="table table-striped table-hover table-bordered" id="surveys">
  <thead>
    <tr>
      <th>Survey name</th>
      <th>Start</th>
      <th>End</th>
      <th>Question total</th>
      <th>Page total</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% if surveys.count > 0 %>
      <% surveys.each do |survey| %>
        <%= render 'survey', survey: survey %>
      <% end %>
    <% else %>
      <tr>
        <td colspan="7" align="center">No survey data found!</td>
      </tr>
    <% end %>
  </tbody>
</table>
        
<div class="row" id="surveys_footer">
  <div class="col-lg-6">
    <% base = (params[:page].present? ? params[:page].to_i-1 : 0)*surveys.per_page %>
    <div class="dataTables_info" id="surveys_info">
      <% if @surveys_count > 0 %>
        Showing <%= base+1 %> to <%= base+surveys.per_page %> of <%= @surveys_count %> entries
      <% end %>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="dataTables_paginate paging_bootstrap pagination">
      <%= pagination_links(surveys, :params => {:controller => controller_name, :action => action_name, :survey => {:name => (params[:survey][:name] if params[:user].present?), :period_start => (params[:survey][:period_start] if params[:user].present?), :period_end => (params[:survey][:period_end] if params[:user].present?), :status => (params[:survey][:status] if params[:user].present?)}}) %>
    </div>
  </div>
</div>

app/views/surveys/add_page.js.erb
<% params[:cancel] ||= false %>
<% unless params[:cancel] %>
	$("#set-page-form").html("<%= j(render '/wizards/set_page') %>")
	$("#close-page-link").removeClass("hide")
	set_hide_button()
	$('html, body').animate({
    scrollTop: $("#set-page-form").offset().top
	}, 2000);
<% else %>
	$("#set-page-form").html("")
	$("#close-page-link").addClass("hide")
<% end %>

Query.fn.preventDoubleSubmission = function() {
  $(this).on('submit',function(e){
    var $form = $(this);

    if ($form.data('submitted') === true) {
      // Previously submitted - don't submit again
      e.preventDefault();
    } else {
      // Mark it so that the next submit can be ignored
      $form.data('submitted', true);
    }
  });

  // Keep chainability
  return this;
};
$('form').preventDoubleSubmission();

app/views/surveys/add_question.js.erb
<% params[:cancel] ||= false %>
<% unless params[:cancel] %>
	$("#set-question-form").html("<%= j(render '/wizards/set_question') %>")
	$("#close-question-link").removeClass("hide")
	$('html, body').animate({
    scrollTop: $("#set-question-form").offset().top
	}, 2000);
<% else %>
	$("#set-question-form").html("")
	$("#close-question-link").addClass("hide")
<% end %>

Query.fn.preventDoubleSubmission = function() {
  $(this).on('submit',function(e){
    var $form = $(this);

    if ($form.data('submitted') === true) {
      // Previously submitted - don't submit again
      e.preventDefault();
    } else {
      // Mark it so that the next submit can be ignored
      $form.data('submitted', true);
    }
  });

  // Keep chainability
  return this;
};
$('form').preventDoubleSubmission();

app/views/surveys/manage_logical.js.erb
<% if params[:section] == "remove" %>
	<% unless @error.present? %>
		$("#logical-preview-<%= params[:id].to_s %>").remove()
	<% end %>

<% elsif params[:section] == "update" %>
	<% unless @error.present? %>
		$("#set-logical-form").html("")
		$("#logical-preview-<%= params[:id].to_s %>").replaceWith("<%= j(render '/questions/logical', logical: params[:logical], id: params[:logical][:target], disabled: true) %>")
	<% end %>

<% end %>

app/views/surveys/manage_page.js.erb
<% params[:is_background] = params[:is_background].present? ? params[:is_background].to_s : 'false' %>
<% if params[:section] == "remove" %>
	<% unless @error.present? %>
		$("#<%= params[:is_background]=='true' ? 'background' : 'page' %>-preview-<%= params[:id].to_s %>").remove()
	<% end %>

<% elsif params[:section] == "update" %>
	<% unless @error.present? %>
		$("#set-<%= params[:is_background]=='true' ? 'background' : 'page' %>-form").html("")
		$("#<%= params[:is_background]=='true' ? 'background' : 'page' %>-preview-<%= params[:id].to_s %>").replaceWith("<%= j(render '/questions/page', page: params[:pages], id: params[:pages][:id], is_background: params[:is_background]) %>")
	<% end %>

<% end %>

app/views/surveys/preview.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="ThemeBucket">
    <link rel="shortcut icon" href="/assets/favicon.png">

    <title>eSurvey</title>

    <!--Core CSS -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <script data-turbolinks-track="true" src="/assets/jquery.js?body=1"></script>
    
    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]>
    <script src="js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <% current_page = session["#{current_user.id.to_s}"]['pages'][params[:id].to_i] %>
  <% questions = session["#{current_user.id.to_s}"]['question'] %>
  <% background = current_page['background'].gsub("public/","/") if current_page.present? && current_page['background'].present? %>
  <%# set_background = (current_page['color'].present? ? "background: #{current_page['color']};" : "background: url('#{background}') no-repeat fixed; background-size: 100%;") %>
  <% set_background = (current_page['color'].present? ? "background: #{current_page['color']};" : "background: url('#{background}') center center fixed; background-size: cover;") %>
  <body style="<%= set_background %>">

    <% if current_page.present? %>
      <div class="container current-page">
        <%= render "/questions/page", page: current_page, id: params[:id], is_background: true, exclude_action: true %>
      </div>
      
      <div class="container">
        <% if current_page['questions'].present? %>
          <% current_page['questions'].each do |id| %>
            <% question = questions[id.to_i] %>
            <%= render "/questions/index", question: question, id: id, disabled: true, exclude_action: true if question.present? %>
          <% end %>
        <% end %>

        <div class="form-group">
          <%= (link_to "Previous", preview_surveys_path((params[:id].to_i-1)), class: "btn btn-primary pull-left") if session["#{current_user.id.to_s}"]['pages'][(params[:id].to_i - 1)].present? %>
        </div>

        <div class="form-group">
          <%= (link_to "Next", preview_surveys_path((params[:id].to_i+1)), class: "btn btn-primary pull-right") if session["#{current_user.id.to_s}"]['pages'][(params[:id].to_i + 1)].present? %>
        </div>
    	</div>
    <% else %>
    	<p>No Content Here</p>
    <% end %>

    <!-- Placed js at the end of the document so the pages load faster -->

    <!--Core js-->
    <%= javascript_tag render(:template => 'surveys/new.js', :formats => [:js]) %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script type="text/javascript">
      jQuery(document).ready(function() {
        DraggablePortlet.init("<%= reorder_surveys_path %>");
        
        $("ul[role=tablist]").children("li").click(function(){
          updateLogic()
        })
      });

      $(document).ready(function(){     
        set_slider()
        set_datepicker_preview()
        set_timepicker_preview()
      })
    </script>
  </body>
</html>

app/views/surveys/reorder.js.erb
$("#<%= @div_id %>").html("<%= j(render @render_view, @send_params) %>")
DraggablePortlet.init("<%= reorder_surveys_path %>")

app/views/surveys/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="ThemeBucket">
    <link rel="shortcut icon" href="/assets/favicon.png">

    <title>eSurvey</title>

    <!--Core CSS -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <script data-turbolinks-track="true" src="/assets/jquery.js?body=1"></script>
    
    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]>
    <script src="js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <% pages = @survey.survey_pages %>
  <% params[:page] = 1 unless params[:page].present? %>
  <% current_page = pages.select{|page| page if params[:page].to_i == page.order}[0] %>
  <% questions = @survey.survey_questions %>
  <% background = current_page.background #.gsub("public/","/") if current_page.present? && current_page.background.present? %>
  <%# set_background = (current_page.color.present? ? "background: #{current_page.color};" : "background: url('#{background}') no-repeat; background-size: 100%;") + " margin-bottom: 50px !important;" %>
  <% set_background = (current_page.color.present? ? "background: #{current_page.color};" : "background: url('#{background}') center center fixed; background-size: cover;") + " margin-bottom: 50px !important;" %>
  <body style="<%= set_background %>">
    <%#= session[current_user.id.to_s]['response'] %>

    <% if current_page.present? %>
      <%= form_tag pages.last.order.to_i==params[:page].to_i ? responses_path(id: params[:id]) : init_survey_responses_path(id: params[:id]), class: "form-horizontal", multipart: true do %>
        <div class="container current-page">
          <%= render "/questions/page", page: current_page, id: current_page.id, is_background: true, exclude_action: true, disabled: false %>
        </div>
        
        <div class="container">
          <% if current_page.survey_questions.present? %>
            <% current_page.survey_questions.each do |question| %>
              <%= render "/questions/index", question: question, id: question.id, disabled: @survey.status == "open" ? false : true, exclude_action: true if question.present? %>

              <% if question.varians["logical"].present? && question.varians["logical"].to_i == 1 %>
                <div id="question-logical-<%= question.id %>"></div>
                <script type="text/javascript">
                  <% if question.varians["logical_value"].present? %>
                    <% exclude_id = [] %>
                    <% question.varians["logical_value"].each do |id, values| %>
                      $("#response_<%= question.id %>_<%= question.question_type %>_<%= question.varians['option'][values['answer']]['label'] %>").click(function(){
                        $("#question-logical-<%= question.id %>").html("")
                        $("#question-logical-<%= question.id %>").html("<%= j(render '/questions/index', question: questions.as_json.select{|question_select| question_select if question_select['varians']['session_id']==values['question']}.first, id: values['question'], disabled: @survey.status == 'open' ? false : true, exclude_action: true) if question.present? %>")
                      })
                      <% exclude_id << values['answer'] %>
                    <% end %>

                    <% question.varians["option"].each do |id, option| %>
                      <% unless exclude_id.include?(id) %>
                        $("#response_<%= question.id %>_<%= question.question_type %>_<%= option['label'] %>").click(function(){
                          $("#question-logical-<%= question.id %>").html("")
                        })
                      <% end %>
                    <% end %>
                  <% end %>
                </script>
              <% end %>
            <% end %>
          <% end %>

          <div class="form-group">
            <%= hidden_field_tag "pages[current]", params[:page].to_i %>
            <%= hidden_field_tag "pages[next]", params[:page].to_i+1 if pages.select{|page| page if params[:page].to_i+1 == page.order}[0].present? %>

            <%= (link_to "Previous", survey_path(params[:id], page: params[:page].to_i-1), class: "btn btn-primary pull-left") if pages.select{|page| page if params[:page].to_i-1 == page.order}[0].present? %>

            <% if @survey.status == "open" %>
              <%= button_tag pages.last.order.to_i==params[:page].to_i ? "Submit" : "Next", type: :submit, class: "btn btn-primary pull-right" %>
            <% else %>
              <%= (link_to "Next", survey_path(params[:id], page: params[:page].to_i+1), class: "btn btn-primary pull-right") if pages.select{|page| page if params[:page].to_i+1 == page.order}[0].present? %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>No Content Here</p>
    <% end %>

    <!-- Placed js at the end of the document so the pages load faster -->

    <!--Core js-->
    <%= javascript_tag render(:template => 'surveys/new.js', :formats => [:js]) %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script type="text/javascript">
      jQuery(document).ready(function(){     
        set_slider()
        set_datepicker_preview()
        set_timepicker_preview()
      })
    </script>
  </body>
</html>