config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    collection do
      post :search
      get :search
    end
  end

  resources :responses do
    collection do
      post :filter
      get :filter
      post :init_survey
    end
  end
  
  resources :media_socials

  post '/add_user' => "users#create"
  put "/profiles" => "users#update_profile"
  get "/profile" => "users#profile"

  get "set_language/change_locale"

  root 'dashboard#index'

  resources :surveys do
    collection do
      post :filter
      get :filter

      get "status/:id" => "surveys#force_status", as: :force

      post :get_view
      get :reload
      post :reorder
      get :question_list
      get "preview/:id" => "surveys#preview", as: :preview
      get :add_row
      get :set_enable
      get :set_survey_session
      get :question_detail
      get :question_page
      get :reset_session
      
      post :set_question
      get :edit_question
      get :add_question
      get "manage_question/:section" => "surveys#manage_question", as: :manage_question
      post "manage_question/:section" => "surveys#manage_question", as: :manage_question_post
      
      post :set_logical
      get :edit_logical
      get :add_logical
      get "manage_logical/:section" => "surveys#manage_logical", as: :manage_logical
      post "manage_logical/:section" => "surveys#manage_logical", as: :manage_logical_post
      
      post :set_page
      get :edit_page
      get :add_page
      get "manage_page/:section" => "surveys#manage_page", as: :manage_page
      post "manage_page/:section" => "surveys#manage_page", as: :manage_page_post
    end
  end

end

app/views/layouts/_header.html.erb
<!--header start-->
<header class="header fixed-top clearfix">
  <!--logo start-->
  <div class="brand">
    <%= link_to (image_tag "logo.png", title: "eSurvey"), root_path, class: "logo" %>
    <div class="sidebar-toggle-box">
      <div class="fa fa-bars"></div>
    </div>
  </div>
  <!--logo end-->

  <div class="top-nav clearfix">
    <!--search & user info start-->
    <ul class="nav pull-right top-menu">
      <li>
        <!-- <input type="text" class="form-control search" placeholder=" Search"> -->
      </li>
      <!-- user login dropdown start-->
      <li class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
          <!-- <img alt="" src="/assets/avatar1_small.jpg"> -->
          <img alt="" src="<%= current_user.image_url(:mini) if current_user.image? %>" onerror="this.src='/assets/default-user.png'">
          <span class="username"><%= current_user.name %></span>
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu extended logout">
          <li>
            <%= link_to profile_path do %>
              <i class="fa fa-user"></i>Profile
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-key"></i> Log Out
            <% end %>
          </li>
        </ul>
      </li>
      <!-- user login dropdown end -->
    </ul>
    <!--search & user info end-->
  </div>
</header>
<!--header end-->

app/views/layouts/_sidebar.html.erb
<!--sidebar start-->
<aside>
  <div id="sidebar" class="nav-collapse">
    <!-- sidebar menu start-->
    <div class="leftside-navigation">
      <ul class="sidebar-menu" id="nav-accordion">
        <li>
        	<%= link_to root_path, class: (controller_name == "dashboard" ? "active" : "") do %>
            <i class="fa fa-dashboard"></i>
            <span>Dashboard</span>
          <% end %>
        </li>
        <% if current_user.role == "admin" %>
          <li>
          	<%= link_to users_path, class: (controller_name == "users" && action_name != "profile" ? "active" : "") do %>
              <i class="fa fa-users"></i>
              <span>User Management</span>
            <% end %>
          </li>
        <% end %>
        <li>
        	<%= link_to surveys_path, class: (controller_name == "surveys" ? "active" : "") do %>
            <i class="fa fa-bullhorn"></i>
            <span>Survey</span>
          <% end %>
        </li>
        <% if current_user.role == "admin" %>
          <li>
          	<%= link_to responses_path, class: (controller_name == "responses" ? "active" : "") do %>
              <i class="fa fa-comments-o"></i>
              <span>Response</span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>        
    <!-- sidebar menu end-->
  </div>
</aside>
<!--sidebar end-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <link rel="shortcut icon" href="/assets/favicon.png">

    <title>eSurvey</title>

    <!--Core CSS -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <script data-turbolinks-track="true" src="/assets/jquery.js?body=1"></script>
    
    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]>
    <script src="js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body class="<%= 'login-body' unless user_signed_in? %>">

      <!-- <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t(:language)%><b class="caret"></b></a>
      <ul class="">
        <li> <%= link_to "English", set_language_change_locale_url(locale: 'en'), 'data-no-turbolink' => true  %></li>
        <li> <%= link_to "Indonesia", set_language_change_locale_url(locale: 'id'), 'data-no-turbolink' => true  %></li>
     </ul> -->

    <% if user_signed_in? %>
      <section id="container">
        <%= render "layouts/header" %>
        <%= render "layouts/sidebar" %>

        <!--main content start-->
        <section id="main-content">
          <section class="wrapper">
          <!-- page start-->
            <div class="row" style="<%= 'display:none;' unless flash.count.to_i > 0 %>">
              <div class="col-md-12">
                <div id="error_explanation-second">
                  <%- flash.each do |name, msg| -%>
                    <%= content_tag :h2, msg, id: "flash_#{name}", class: "flash_content" if msg.is_a?(String) %>
                  <%- end -%> 
                </div>
              </div>
            </div>

            <div class="row">
              <%= yield %>
            </div>
          <!-- page end-->
          </section>
        </section>
        <!--main content end-->
      </section>
    <% else %>
      <div class="container">
        <%= yield %>
      </div>
    <% end %>

   <!-- Placed js at the end of the document so the pages load faster -->

   <!--Core js-->
   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <script type="text/javascript">
      setTimeout(function(){ $("#error_explanation-second").parent("div.col-md-12").parent("div.row").slideUp("slow") }, 5000);
      
      $('.dpYears').datepicker();

      <% if user_signed_in? %>
        var settings = {
          headerTag: "h2",
          bodyTag: "section",
          transitionEffect: "slideLeft",

          /* Events */
          onStepChanged: function (event, currentIndex, priorIndex) {
            $.ajax({
              type:'GET',
              url: "<%= reload_surveys_path %>",
              success:function(data){
                data
              }
            });
          },
          onFinishing: function (event, currentIndex) {
            $("#new_survey_submit").prop('disabled', false)
            $("#new_survey_submit").click()
          }
        };

        $(function (){
          $("#wizard").steps(settings);
        });
      <% end %>
      
      $("li.dropdown").click(function(){
        $(this).toggleClass("open");
      })
      $("button.dropdown-toggle").click(function(){
        $(this).parent("div").toggleClass("open");
      })
      
      $(document).ajaxSend(function() {
        if($(".ajax-feeds-loader").length == 0){
          set_loader()
        }
      }).ajaxComplete(function() {
        setTimeout(function(){$(".ajax-loader").remove();},1000);
      });

      function set_loader(){
        $("body").append("<div class='ajax-loader'></div>")
      }

      <% if controller_name == "dashboard" %>
        <% if @all_one_year_responses > 0 && @one_year_responses > 0 %>
          if ($.fn.plot) {
            // DONUT
            var dataPie = [{
              label: "Response",
              data: <%= ((@one_year_responses.to_f/@all_one_year_responses.to_f)*100).ceil %>
            }, {
              label: "Unresponse",
              data: <%= (((@all_one_year_responses-@one_year_responses).to_f/@all_one_year_responses.to_f)*100).floor %>
            }];

            $.plot($(".sm-pie"), dataPie, {
              series: {
                pie: {
                  innerRadius: 0.6,
                  show: true,
                  stroke: {
                    width: 0.1,
                    color: '#ffffff'
                  }
                }
              },

              legend: {
                show: true
              },
              grid: {
                hoverable: true,
                clickable: true
              },

              // colors: ["#ffdf7c", "#b2def7", "#efb3e6"]
              colors: ["#efb3e6", "#b2def7"]
            });
          }
        <% end %>

        $(".bar-stats").attr("style", "height: "+$(".bar-legend").height()+"px")
        $(".top-stats-panel").attr("style", "height: "+($(".daily-sales-info").height()+$(".bar-legend").height()+50)+"px")

        $('.progress-stat-bar li').each(function () {
          $(this).attr("style", "height: "+($(".bar-legend").height()-2)+"px")
          $(this).find('.progress-stat-percent').animate({
            height: $(this).attr('data-percent')
          }, 1000);
        });
      <% end %>
    </script>

    <% if controller_name == "users" && (action_name == "create" || action_name == "update") %>
      <script type="text/javascript">
        <% if @user.present? %>
          $("#myModal").modal('show')
        <% end %>
      </script>
    <% end %>
    
    <% if controller_name == "surveys" && (action_name == "new") %>
      <script type="text/javascript">
        setTimeout("$('.default-date-picker').datepicker();", 1000)
        $(document).ready(function(){
          <% if session["#{current_user.id.to_s}"].present? %>

            <% if session["#{current_user.id.to_s}"]['pages'].present? %>
              $('#wizard-t-1').parent('li').removeClass('disabled').children('a').click()
            <% end %>

            <% if session["#{current_user.id.to_s}"]['logical'].present? %>
              $('#wizard-t-1').parent('li').removeClass('disabled').children('a').click()
              $('#wizard-t-2').parent('li').removeClass('disabled').children('a').click()
            <% end %>

            <% session["#{current_user.id.to_s}"]['pages'].each do |key, pages| %>
              <% if pages['background'].present? || pages['color'].present? %>
                $('#wizard-t-1').parent('li').removeClass('disabled').children('a').click()
                $('#wizard-t-2').parent('li').removeClass('disabled').children('a').click()
                $('#wizard-t-3').parent('li').removeClass('disabled').children('a').click()
                <% break %>
              <% end %>
            <% end %>
          <% end %>
        });
      </script>
    <% end %>
    <script type="text/javascript">
      jQuery(document).ready(function() {
        DraggablePortlet.init("<%= reorder_surveys_path %>");
        
        $("ul[role=tablist]").children("li").click(function(){
          updateLogic()
        })
      });

      <% if controller_name == "surveys" && action_name == "new" %>
        $(document).ready(function(){        
          set_slider()
          set_datepicker_preview()
          set_timepicker_preview()
        })
      <% end %>
    </script>
  </body>
</html>